# Generated by Django 5.2 on 2025-04-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.IntegerField(help_text='Odometer reading at time of service')),
                ('description', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('labor_details', models.TextField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('interval_type', models.CharField(choices=[('mileage', 'Mileage'), ('date', 'Date'), ('both', 'Mileage and Date')], max_length=10)),
                ('mileage_interval', models.IntegerField(blank=True, help_text='Mileage interval between services', null=True)),
                ('time_interval_days', models.IntegerField(blank=True, help_text='Days between services', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_odometer', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='vehicles.vehicle')),
            ],
        ),
    ]
