# Generated by Django 5.2 on 2025-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('maintenance', '0002_maintenancerecord_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='maintenance_records', to='expenses.expense'),
        ),
    ]
